### ISSUE TITLE
Syntax to add versioned router

### ISSUE THREAD

**Issue by amitguptagwl** [node-muneem/muneem#7]
A route can be registered with the following syntax

```yaml
- route: 
    uri: "/list/transactions/:creditCard(:credit-card:)"
    with:
        maxLength: 1024 * 1024
    to: CreditCardService
    after: [ authentication, monitoring ]
    then: compress
```

We've to integrate other features of [anumargak](https://github.com/node-muneem/anumargak/) router.

* Named expression
* Versioned routes

And we've to decide the correct syntax to use them with muneem framework.
