### ISSUE TITLE
Change the "maxLength" route registration syntax

### ISSUE THREAD

**Issue by amitguptagwl** [node-muneem/muneem#8]
A route can be registered with the following syntax

- route: 
    uri: "/list/transactions/:creditCard(:credit-card:)"
    maxLength: 1024 * 1024
    to: CreditCardService
    after: [ authentication, monitoring ]
    then: compress
```

To improve readability, we want to change the framework to support following syntax

A route can be registered with the following syntax

- route: 
    uri: "/list/transactions/:creditCard(:credit-card:)"
    with:
        maxLength: 1024 * 1024
    to: CreditCardService
    after: [ authentication, monitoring ]
    then: compress
```

Check [routesManager](https://github.com/node-muneem/muneem/blob/master/src/routesManager.js) to find the relevant code. Please updates the tests accordingly.
